version: '3'

services:
  backend:
    build: .
    hostname: backend
    container_name: backend
    links:
      - db
    ports:
      - '8080:80'
    environment:
      HOST_IP: "52.206.174.112"
      HOST_PORT: "8080"
    volumes:
      - ./frontend/images:/images
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "32001:3306"
    environment:
      MYSQL_USER: user 
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123
    volumes:
      - ./database:/tmp/database
    command: mysqld --init-file="/tmp/database/F2F.sql"

  frontend:
    hostname: frontend
    container_name: frontend
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./frontend:/app
      
